game: chess
version: v2
file_name: train

mcts:
  num_rollout: 256
  mcts_batch_size: 32

training:
  duration: 6.0
  iterations: null
  steps_per_iter: 500
  train_batch_size: 128
  replay_buffer_max_size: 50000
  num_selfplay: 8

logging:
  kaggle: true
  verbose: false
  log_interval: 1

hf:
  push_to_hf: true
  load_from_hf: true
  repo_id: williamalxndr/chess-trained-network