game: chess
version: V2
file_name: best

mcts:
  num_rollout: 800
  mcts_batch_size: 64
  num_selfplay: 4

training:
  duration: 5
  steps_per_iter: 200
  train_batch_size: 64
  replay_buffer_max_size: 50000

logging:
  kaggle: true
  log_interval: 5